recipe: default.v1

assistant_id: 20251120-121113-thin-bush

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3
  - name: DIETClassifier
    epochs: 25
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: RulePolicy

logging:
  level: "INFO"


